### ISSUE TITLE
Erigon tries to create blocks with no Deposits

### ISSUE THREAD

**Issue by mmontour1306** [bobanetwork/op-erigon#60]
Branch: head of boba-develop (`a02cc8f162e385db86c323c2ec0d38e28230425b`)

Adding this debug line:

```
diff --git a/eth/stagedsync/stage_mining_exec.go b/eth/stagedsync/stage_mining_exec.go
index db2445a7c..c629cb9c9 100644
--- a/eth/stagedsync/stage_mining_exec.go
+++ b/eth/stagedsync/stage_mining_exec.go
@@ -5,6 +5,7 @@ import (
        "fmt"
        "io"
        "math/big"
+       "runtime/debug"
        "sync/atomic"
        "time"
 
@@ -161,6 +162,7 @@ func SpawnMiningExecStage(s *StageState, tx kv.RwTx, cfg MiningExecCfg, quit <-c
                                }
 
                                if !txs.Empty() {
+                                       log.Debug("stage_mining_exec addTransactionsToMiningBlock", "block", current.Header.Number, "numDeposits", len(current.Deposits), "callstack", string(debug.Stack()))
                                        logs, stop, err := addTransactionsToMiningBlock(logPrefix, current, cfg.chainConfig, cfg.vmConfig, getHeader, cfg.engine, txs, cfg.miningState.MiningConfig.Etherbase, ibs, quit, cfg.interrupt, cfg.payloadId, logger)
                                        log.Debug("addTransactionsToMiningBlock (regular)", "err", err, "logs", logs, "stop", stop)
                                        if err != nil {
```

shows that `SpawnMiningExecStage` is being called from `eth/backend.go` along two different paths, and on one path there are no Deposits in the current block (not valid for Bedrock).

Bad:
`
ops-bedrock-l2-1  | [DBUG] [10-20|20:33:33.967] stage_mining_exec addTransactionsToMiningBlock block=210 numDeposits=0 callstack="goroutine 11795 [running, locked to thread]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/ledgerwatch/erigon/eth/stagedsync.SpawnMiningExecStage(_, {_, _}, {{0x31079d8, 0xc001451e10}, {0xc000e0b6f8, 0xc0006132c0, 0xc000613320, 0x0, 0xc000e04280}, ...}, ...)\n\t/app/v3-erigon/eth/stagedsync/stage_mining_exec.go:165 +0xf75\ngithub.com/ledgerwatch/erigon/eth/stagedsync.MiningStages.func7(0x80?, 0x61?, 0x28bb6aa?, {0xf?, 0x31149b0?}, {0x3122a00, 0xc001db4aa0}, {0x31082c8, 0xc00007e160})\n\t/app/v3-erigon/eth/stagedsync/stagebuilder.go:61 +0xc6\ngithub.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc000756180, 0xc0005ac640, {0x0?, 0x0}, {0x3122a00?, 0xc001db4aa0}, 0x0?, 0x0?)\n\t/app/v3-erigon/eth/stagedsync/sync.go:430 +0x15f\ngithub.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc000756180, {0x0, 0x0}, {0x3122a00, 0xc001db4aa0}, 0x4?)\n\t/app/v3-erigon/eth/stagedsync/sync.go:331 +0x275\ngithub.com/ledgerwatch/erigon/turbo/stages.MiningStep({0x30f5518?, 0xc000058070?}, {0x31079d8?, 0xc001451e10?}, 0x4754a5?, {0xc000f11f60, 0x8})\n\t/app/v3-erigon/turbo/stages/stageloop.go:350 +0x177\ngithub.com/ledgerwatch/erigon/eth.(*Ethereum).StartMining.func4.1()\n\t/app/v3-erigon/eth/backend.go:1084 +0x3e\ncreated by github.com/ledgerwatch/erigon/eth.(*Ethereum).StartMining.func4\n\t/app/v3-erigon/eth/backend.go:1084 +0x655\n"
`

Good:
`
ops-bedrock-l2-1  | [DBUG] [10-20|20:33:34.006] stage_mining_exec addTransactionsToMiningBlock block=210 numDeposits=1 callstack="goroutine 11801 [running, locked to thread]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/ledgerwatch/erigon/eth/stagedsync.SpawnMiningExecStage(_, {_, _}, {{0x31079d8, 0xc001451e10}, {0xc000e0b6f8, 0xc000b20c00, 0xc000b20c60, 0xc000b20cc0, 0xc002470780}, ...}, ...)\n\t/app/v3-erigon/eth/stagedsync/stage_mining_exec.go:165 +0xf75\ngithub.com/ledgerwatch/erigon/eth/stagedsync.MiningStages.func7(0x80?, 0x87?, 0x28bb6aa?, {0xf?, 0x31149b0?}, {0x3122a00, 0xc0007c6a50}, {0x31082c8, 0xc00007e160})\n\t/app/v3-erigon/eth/stagedsync/stagebuilder.go:61 +0xc6\ngithub.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc002438780, 0xc0007c68c0, {0x0?, 0x0}, {0x3122a00?, 0xc0007c6a50}, 0x0?, 0x0?)\n\t/app/v3-erigon/eth/stagedsync/sync.go:430 +0x15f\ngithub.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc002438780, {0x0, 0x0}, {0x3122a00, 0xc0007c6a50}, 0x2?)\n\t/app/v3-erigon/eth/stagedsync/sync.go:331 +0x275\ngithub.com/ledgerwatch/erigon/turbo/stages.MiningStep({0x30f54e0?, 0xc000dfa7d0?}, {0x31079d8?, 0xc001451e10?}, 0xc000416b68?, {0xc000f11f60, 0x8})\n\t/app/v3-erigon/turbo/stages/stageloop.go:350 +0x177\ngithub.com/ledgerwatch/erigon/eth.New.func10(0xc00155a8f0, 0xc002e17800)\n\t/app/v3-erigon/eth/backend.go:635 +0xd7d\ngithub.com/ledgerwatch/erigon/turbo/builder.NewBlockBuilder.func1()\n\t/app/v3-erigon/turbo/builder/block_builder.go:31 +0xc4\ncreated by github.com/ledgerwatch/erigon/turbo/builder.NewBlockBuilder\n\t/app/v3-erigon/turbo/builder/block_builder.go:28 +0x10a\n"
`

Expected: this function should only be called on the 'good' path so that it is able to produce a valid block, and without executing unnecessary EVM transactions.

I haven't looked at what happens (or should happen) if this Erigon is run as a standard client without the Bedrock features enabled.

**Comment by jyellick** [comment]
Are you observing this in the e2e tests? Or the devnet? Is this sequencer / verifier / both?

**Comment by mmontour1306** [comment]
Local devnet, sequencer. I haven't checked the verifier or e2e. I have a workaround so this issue isn't blocking anything for me.
